config/routes.rb
ClockingOff::Application.routes.draw do

  root :to => "calendar#index"

  devise_for :users

  resources :projects

  resources :clients

  resources :events, :except => [:new, :create]

  match '/timesheet' => 'calendar#timesheet'
  match '/timesheet/print' => 'calendar#print_timesheet'

  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar,
    :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}

  match '/calendar(/:year(/:month(/:day)))' => 'calendar#day', :as => :calendar_day,
    :constraints => {:year => /\d{4}/, :month => /\d{1,2}/, :day => /\d{1,2}/}

  scope '(:date)', :date => /\d{4}-\d{1,2}-\d{1,2}/ do
    resources :events, :only => [:new, :create]
  end

end

app/controllers/calendar_controller.rb
class CalendarController < ApplicationController

  def index
    @month = (params[:month] || (Time.zone || Time).now.month).to_i
    @year = (params[:year] || (Time.zone || Time).now.year).to_i

    @shown_month = Date.civil(@year, @month)

    @event_strips = Event.for_user(current_user).event_strips_for_month(@shown_month)
  end

  def day
    @events = Event.for_user(current_user).on_date(Time.local(params[:year], params[:month], params[:day]))
  end

  def timesheet
    start_date = Date.parse(params[:ts_start_date])
    end_date = Date.parse(params[:ts_end_date])
    client = Client.find(params[:client])
    @timesheet = Timesheet.new(current_user, client, start_date, end_date)
  end

  def print_timesheet
    start_date = Date.parse(params[:start_date])
    end_date = Date.parse(params[:end_date])
    client = Client.find(params[:client])
    @timesheet = Timesheet.new(current_user, client, start_date, end_date)
    render :layout => false
  end

end

app/helpers/calendar_helper.rb
module CalendarHelper

  def month_link(month_date)
    link_to(I18n.localize(month_date, :format => "%B"), {:month => month_date.month, :year => month_date.year})
  end

  # custom options for this calendar
  def event_calendar_opts
    {
      :year => @year,
      :month => @month,
      :event_strips => @event_strips,
      :month_name_text => I18n.localize(@shown_month, :format => "%B %Y"),
      :previous_month_text => "&laquo; #{month_link(@shown_month.prev_month)}",
      :next_month_text => "#{month_link(@shown_month.next_month)} &raquo;",
      :link_to_day_action => "day"
    }
  end

  def event_calendar
    # args is an argument hash containing :event, :day, and :options
    calendar event_calendar_opts do |args|
      event = args[:event]
      %(<a href="/events/#{event.id}" title="#{h(event.name)}" data-remote="true">#{h(event.name)} : #{h(event_time(event))}</a>)
    end
  end

  def event_hours(event)
    hours = event.hours % 1 == 0 ? event.hours.to_i : "%.2f" % event.hours
    "#{hours} hrs"
  end

  def event_time(event)
    "#{event.start_at.hour}.#{event.start_at.min}-#{event.end_at.hour}.#{event.end_at.min} (#{event_hours(event)})"
  end

  def full_date
    now = Time.now
    year = params[:year] || @year || now.year
    month = params[:month] || @month || now.month
    day = params[:day] || @day || now.day
    Time.local(year, month, day).strftime("%A %d %B %Y")
  end

end

# Patched to make remote calls from calendar day links.
#
module EventCalendar
  module CalendarHelper
    def day_link(text, date, day_action)
      link_to(text, params.merge(:action => day_action, :year => date.year, :month => date.month, :day => date.day),
        :class => 'ec-day-link', :remote => true)
    end
  end
end

app/views/calendar/_day.html.erb
<%= render :partial => 'shared/modal_toolbar' %>
<div>
  <h1>Work for <%= full_date %></h1>
  <table>
    <tr>
      <th>Hours</th>
      <th>Name</th>
      <th></th>
    </tr>
    <% @events.each do |event| -%>
    <tr>
      <td><%= event_time event %></td>
      <td><%= event.name %></td>
      <td>
        <%= link_to "Show", event_path(event), :remote => true %>&nbsp;
        <%= link_to "Edit", edit_event_path(event), :remote => true %>&nbsp;
        <%= link_to "Destroy", event_path(event), :method => :delete, :remote => true %>
      </td>
    </tr>
    <% end -%>
  </table>
  <%= link_to "+ Add", new_event_path("#{params[:year]}-#{params[:month]}-#{params[:day]}"), :remote => true %>
</div>

app/views/calendar/_toolbar.html.erb
<ul class="toolbar">
  <li><%= link_to "Manage Clients", clients_path, :remote => true %></li>
  <li><%= link_to "Manage Projects", projects_path, :remote => true %></li>
</ul>
<%= form_tag '/timesheet' do -%>
<ul class="toolbar">
  <li>Timesheet from:&nbsp;<%= calendar_date_select_tag "ts_start_date", @ts_start_date.to_s %></li>
  <li>to:&nbsp;<%= calendar_date_select_tag "ts_end_date", @ts_end_date.to_s %></li>
  <li>Client:&nbsp;<%= select_tag "client", options_for_select(@clients.map{|c|[c.name,c.id]}) %></li>
  <li><%= submit_tag "Go" %></li>
</ul>
<% end -%>

app/views/calendar/index.html.erb
<%= raw(event_calendar) %>

app/views/calendar/print_timesheet.html.erb
<%
  start_date = @timesheet.start_date.strftime("%d-%m-%Y")
  end_date = @timesheet.end_date.strftime("%d-%m-%Y")
  heading = "Timesheet (#{@timesheet.client.name}, #{start_date} to #{end_date})"
-%>
<html>
  <head>
    <title><%= heading %></title>
  </head>
  <body style="font: 12pt normal arial, helvetica">
    <h1 style="font-size:18pt;"><%= heading %></h1>
    <p>
      <span style="font-weight:bold">From:&nbsp;</span><%= start_date %>&nbsp;&nbsp;&nbsp;
      <span style="font-weight:bold">To:&nbsp;</span><%= end_date %>
    </p>
    <p><span style="font-weight:bold">Client:&nbsp;</span><%= @timesheet.client.name %></p>

    <table width="90%">
      <tr>
        <th style="width:4cm; border: 1px solid #333; background:#999;">Project</th>
      <% @timesheet.headings.each do |heading| -%>
        <th style="border: 1px solid #333; background:#999"><%= heading %></th>
      <% end -%>
        <th style="border: 1px solid #333; background:#999">Total</th>
      </tr>
      <% @timesheet.hours.keys.sort.each do |project_name| -%>
      <tr>
        <td style="border: 1px solid #333; text-align:center;"><%= project_name %></td>
        <% @timesheet.start_date.upto(@timesheet.end_date) do |date| -%>
        <%
          date_key = date.strftime("%d-%m-%y")
          hours = @timesheet.hours[project_name][date_key]
        -%>
        <td style="border: 1px solid #333;text-align:center"><%= hours ? "%.3f" % hours : "" %></td>
        <% end -%>
        <td style="border: 1px solid #333;text-align:center"><%= "%.3f" % @timesheet.project_hours[project_name] %></td>
      </tr>
      <% end -%>
      <tr>
        <td style="border: 1px solid #333;text-align:center" colspan="<%= @timesheet.headings.size + 1 %>"></td>
        <td style="border: 1px solid #333;text-align:center">Total:&nbsp;<%= "%.3f" % @timesheet.total_hours %> hours</td>
      </tr>
    </table>
  </body>
</html>

app/views/calendar/timesheet.html.erb
<div class="timesheet">
  <h1>Timesheet</h1>
  <p>
    <span class="label">From:</span><%= @timesheet.start_date.strftime("%d/%m/%Y") %>
    &nbsp;&nbsp;&nbsp;
    <span class="label">To:</span><%= @timesheet.end_date.strftime("%d/%m/%Y") %>
  </p>
  <p><span class="label">Client:</span><%= @timesheet.client.name %></p>
  <table>
    <tr>
      <th class="project-heading">Project</th>
    <% @timesheet.headings.each do |heading| -%>
      <th><%= heading %></th>
    <% end -%>
      <th>Total</th>
    </tr>
    <% @timesheet.hours.keys.sort.each do |project_name| -%>
    <tr>
      <td class="project-name"><%= project_name %></td>
      <% @timesheet.start_date.upto(@timesheet.end_date) do |date| -%>
      <%
        date_key = date.strftime("%d-%m-%y")
        hours = @timesheet.hours[project_name][date_key]
      -%>
      <td><%= hours ? "%.3f" % hours : "" %></td>
      <% end -%>
      <td><%= "%.3f" % @timesheet.project_hours[project_name] %></td>
    </tr>
    <% end -%>
    <tr>
      <td colspan="<%= @timesheet.headings.size + 1 %>"></td>
      <td>Total:&nbsp;<%= "%.3f" % @timesheet.total_hours %> hours</td>
    </tr>
  </table>
  <p><%= link_to "Printable version", timesheet_print_path(:client => @timesheet.client.to_param, :start_date => @timesheet.start_date.to_s, :end_date => @timesheet.end_date.to_s) %></p>
</div>