config/routes.rb
ClockingOff::Application.routes.draw do

  root :to => "calendar#index"

  devise_for :users

  resources :projects

  resources :clients

  resources :events, :except => [:new, :create]

  match '/timesheet' => 'calendar#timesheet'
  match '/timesheet/print' => 'calendar#print_timesheet'

  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar,
    :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}

  match '/calendar(/:year(/:month(/:day)))' => 'calendar#day', :as => :calendar_day,
    :constraints => {:year => /\d{4}/, :month => /\d{1,2}/, :day => /\d{1,2}/}

  scope '(:date)', :date => /\d{4}-\d{1,2}-\d{1,2}/ do
    resources :events, :only => [:new, :create]
  end

end

app/views/shared/_header.html.erb
<div class="calendar-header">
  <h1>Clocking Off</h1>
  <%= render :partial => "shared/user_toolbar" %>
  <%= render :partial => "shared/toolbar" %>
</div>

app/views/shared/_modal_toolbar.html.erb
<div class="modal-toolbar">
  <div class="close"><a href="#" onclick="Control.Modal.current.close(); return false;">X</a></div>
</div>

app/views/shared/_toolbar.html.erb
<ul class="toolbar">
  <li><%= link_to "Calendar", calendar_path %></td>
  <li><%= link_to "Manage Clients", clients_path, :remote => true %></li>
  <li><%= link_to "Manage Projects", projects_path, :remote => true %></li>
</ul>
<% if user_signed_in? -%>
<%= form_tag '/timesheet' do -%>
<ul class="toolbar">
  <li>Timesheet from:&nbsp;<%= calendar_date_select_tag "ts_start_date", @ts_start_date.to_s %></li>
  <li>to:&nbsp;<%= calendar_date_select_tag "ts_end_date", @ts_end_date.to_s %></li>
  <li>Client:&nbsp;<%= select_tag "client", options_for_select(@clients.map{|c|[c.name,c.id]}) %></li>
  <li><%= submit_tag "Go" %></li>
</ul>
<% end -%>
<% end -%>

app/views/shared/_user_toolbar.html.erb
<ul class="toolbar">
<% if user_signed_in? -%>
  <li>Logged in as <%= current_user.email %></li>
  <li><%= link_to "Log out", destroy_user_session_path %></li>
<% else -%>
  <li><%= link_to "Log in", new_user_session_path %></li>
  <li><%= link_to "Sign up", new_user_registration_path %></li>
<% end -%>
</ul>