config/routes.rb
ClockingOff::Application.routes.draw do

  root :to => "calendar#index"

  devise_for :users

  resources :projects

  resources :clients

  resources :events, :except => [:new, :create]

  match '/timesheet' => 'calendar#timesheet'
  match '/timesheet/print' => 'calendar#print_timesheet'

  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar,
    :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}

  match '/calendar(/:year(/:month(/:day)))' => 'calendar#day', :as => :calendar_day,
    :constraints => {:year => /\d{4}/, :month => /\d{1,2}/, :day => /\d{1,2}/}

  scope '(:date)', :date => /\d{4}-\d{1,2}-\d{1,2}/ do
    resources :events, :only => [:new, :create]
  end

end

app/models/client.rb
class Client < ActiveRecord::Base
  validates_presence_of :name
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  def index
    @clients = Client.all
  end

  def show
    @client = Client.find(params[:id])
  end

  def new
    @client = Client.new
  end

  def edit
    @client = Client.find(params[:id])
  end

  def create
    @client = Client.new(params[:client])
    @saved = @client.save
    @clients = Client.all if @saved
  end

  def update
    @client = Client.find(params[:id])
    @saved = @client.update_attributes(params[:client])
    @clients = Client.all if @saved
  end

  def destroy
    @client = Client.find(params[:id])
    @client.destroy
    @clients = Client.all
  end
end

app/views/clients/_edit.html.erb
<%= render :partial => 'shared/modal_toolbar' %>
<div>
  <h1>Edit <%= @client.name %></h1>
  <%= form_for @client, :url => client_path(@client.to_param), :method => :post, :remote => true do |form| -%>
  <%= render :partial => 'form', :object => form %>
  <%= form.submit "Update" %>
  <% end -%>
  <%= link_to 'Show', client_path(@client.to_param), :remote => true %>
  <%= link_to 'Back', clients_path, :remote => true %>
</div>

app/views/clients/_form.html.erb
<%= form.error_messages %>

<p>
  <%= label_tag "Name: " %>
  <%= form.text_field :name %>
</p>
<p>
  <%= label_tag "Rate: " %>
  <%= form.text_field :rate, :size => 5 %>
</p>
<p>
  <%= label_tag "Description: " %>
  <%= form.text_area :description %>
</p>

app/views/clients/_index.html.erb
<%= render :partial => 'shared/modal_toolbar' %>
<h1>Listing clients</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th></th>
  </tr>

<% @clients.each do |client| %>
  <tr>
    <td><%= client.name %></td>
    <td><%= client.description %></td>
    <td>
      <%= link_to 'Show', client, :remote => true %>&nbsp;
      <%= link_to 'Edit', edit_client_path(client), :remote => true %>&nbsp;
      <%= link_to 'Destroy', client, :confirm => 'Are you sure?', :method => :delete, :remote => true %>
    </td>
  </tr>
<% end %>
</table>

<br />

<%= link_to '+ Add Client', new_client_path, :remote => true %>

app/views/clients/_new.html.erb
<%= render :partial => 'shared/modal_toolbar' %>
<div>
  <h1>New client</h1>
  <%= form_for :client, :url => clients_path, :method => :post, :remote => true do |form| -%>
  <%= render :partial => 'form', :object => form %>
  <%= form.submit "Save" %>
  <% end -%>
  <%= link_to 'Back', clients_path, :remote => true %>
</div>

app/views/clients/_show.html.erb
<%= render :partial => 'shared/modal_toolbar' %>
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @client.name %>
</p>

<p>
  <b>Description:</b>
  <%= @client.description %>
</p>


<%= link_to 'Edit', edit_client_path(@client), :remote => true %> |
<%= link_to 'Back', clients_path, :remote => true %>

app/views/clients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @client.name %>
</p>

<p>
  <b>Description:</b>
  <%= @client.description %>
</p>


<%= link_to 'Edit', edit_client_path(@client) %> |
<%= link_to 'Back', clients_path %>