config/routes.rb
ClockingOff::Application.routes.draw do

  root :to => "calendar#index"

  devise_for :users

  resources :projects

  resources :clients

  resources :events, :except => [:new, :create]

  match '/timesheet' => 'calendar#timesheet'
  match '/timesheet/print' => 'calendar#print_timesheet'

  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar,
    :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}

  match '/calendar(/:year(/:month(/:day)))' => 'calendar#day', :as => :calendar_day,
    :constraints => {:year => /\d{4}/, :month => /\d{1,2}/, :day => /\d{1,2}/}

  scope '(:date)', :date => /\d{4}-\d{1,2}-\d{1,2}/ do
    resources :events, :only => [:new, :create]
  end

end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :client

  validates_presence_of :name
  validates_numericality_of :client_id

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def index
    @projects = Project.all
  end

  def show
    @project = Project.find(params[:id])
  end

  def new
    @project = Project.new
    @clients = Client.all
  end

  def edit
    @project = Project.find(params[:id])
    @clients = Client.all
  end

  def create
    @project = Project.new(params[:project])
    @saved = @project.save
    @projects = Project.all if @saved
  end

  def update
    @project = Project.find(params[:id])
    @saved = @project.update_attributes(params[:project])
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    @projects = Project.all
  end
end

app/views/projects/_edit.html.erb
<%= render :partial => 'shared/modal_toolbar' %>
<div>
  <h1>Edit <%= @project.name %></h1>
  <%= form_for @project, :url => project_path(@project.to_param), :method => :post, :remote => true do |form| -%>
  <%= render :partial => 'form', :object => form %>
  <%= form.submit "Update" %>
  <% end -%>
  <%= link_to 'Show', project_path(@project.to_param), :remote => true %>
  <%= link_to 'Back', projects_path, :remote => true %>
</div>

app/views/projects/_form.html.erb
<%= form.error_messages %>

<p>
  <%= label_tag "Name: " %>
  <%= form.text_field :name %>
</p>
<p>
  <%= label_tag "Client: " %>
<% if @clients.nil? or @clients.empty? -%>
  <%= link_to "Manage Clients", clients_path, :remote => true %>
<% else -%>
  <%= form.select :client_id, @clients.map { |c| [c.name, c.id] } %>
<% end -%>
</p>
<p>
  <%= label_tag "Rate: " %>
  <%= form.text_field :rate, :size => 5 %>
</p>
<p>
  <%= label_tag "Description" %>
  <%= form.text_area :description %>
</p>

app/views/projects/_index.html.erb
<%= render :partial => 'shared/modal_toolbar' %>
<h1>Listing projects</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Client</th>
    <th></th>
  </tr>

<% @projects.each do |project| %>
  <tr>
    <td><%= project.name %></td>
    <td><%= project.client.name %></td>
    <td>
      <%= link_to 'Show', project, :remote => true %>&nbsp;
      <%= link_to 'Edit', edit_project_path(project), :remote => true %>&nbsp;
      <%= link_to 'Destroy', project, :confirm => 'Are you sure?', :method => :delete, :remote => true %>
    </td>
  </tr>
<% end %>
</table>

<br />

<%= link_to '+ Add Project', new_project_path, :remote => true %>

app/views/projects/_new.html.erb
<%= render :partial => 'shared/modal_toolbar' %>
<div>
  <h1>New project</h1>
  <%= form_for :project, :url => projects_path, :method => :post, :remote => true do |form| -%>
  <%= render :partial => 'form', :object => form %>
  <%= form.submit "Save" %>
  <% end -%>
  <%= link_to 'Back', projects_path, :remote => true %>
</div>

app/views/projects/_show.html.erb
<%= render :partial => 'shared/modal_toolbar' %>
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @project.name %>
</p>

<p>
  <b>Description:</b>
  <%= @project.description %>
</p>

<p>
  <b>Client:</b>
  <%= @project.client.name %>
</p>


<%= link_to 'Edit', edit_project_path(@project), :remote => true %> |
<%= link_to 'Back', projects_path, :remote => true %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @project.name %>
</p>

<p>
  <b>Description:</b>
  <%= @project.description %>
</p>

<p>
  <b>Client:</b>
  <%= @project.client.name %>
</p>


<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>